"""add phone number

Revision ID: c9458c5356fc
Revises: 
Create Date: 2026-06-24 12:27:05.069177

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c9458c5356fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
